/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Backtest: typeof import('./pages/Backtest.vue')['default']
    CloseTradeDialog: typeof import('./components/CloseTradeDialog.vue')['default']
    DataCard: typeof import('./components/DataCard.vue')['default']
    FabButton: typeof import('./components/FabButton.vue')['default']
    HelloWorld: typeof import('./pages/Backtest.vue')['default']
    Loader: typeof import('./components/Loader.vue')['default']
    MarketBreadthChart: typeof import('./components/MarketBreadthChart.vue')['default']
    PortfolioEntryDialog: typeof import('./components/PortfolioEntryDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StockChart: typeof import('./components/StockChart.vue')['default']
    TradeChart: typeof import('./components/TradeChart.vue')['default']
    TradesChart: typeof import('./components/TradesChart.vue')['default']
    TradesList: typeof import('./components/TradesList.vue')['default']
  }
}
