package com.skrymer.udgaard.model

enum class StockSymbol(sector: String) {
  MSFT("Technology Services"),
  GOOG("Technology Services"),
  META("Technology Services"),
  ORCL("Technology Services"),
  NFLX("Technology Services"),
  SAP("Technology Services"),
  PLTR("Technology Services"),
  IBM("Technology Services"),
  CRM("Technology Services"),
  INTU("Technology Services"),

//  BRKB("Finance"),
  JPM("Finance"),
  V("Finance"),
  MA("Finance"),
  BAC("Finance"),
  WFC("Finance"),
  MS("Finance"),
  AXP("Finance"),
  HSBC("Finance"),
  GS("Finance"),
  RY("Finance"),

  NVDA("Electronic Technology"),
  AAPL("Electronic Technology"),
  AVGO("Electronic Technology"),
  TSM("Electronic Technology"),
  ASML("Electronic Technology"),
  CSCO("Electronic Technology"),
  GE("Electronic Technology"),
  AMD("Electronic Technology"),
  RTX("Electronic Technology"),
  TXN("Electronic Technology"),

  LLY("Health Technology"),
  JNJ("Health Technology"),
  NVO("Health Technology"),
  ABBV("Health Technology"),
  ABT("Health Technology"),
  NVS("Health Technology"),
  AZN("Health Technology"),
  MRK("Health Technology"),
  ISRG("Health Technology"),
  AMGN("Health Technology"),

  AMZN("Retail Trade"),
  WMT("Retail Trade"),
  COST("Retail Trade"),
  HD("Retail Trade"),
  BABA("Retail Trade"),
  PDD("Retail Trade"),
  TJX("Retail Trade"),
  MELI("Retail Trade"),
  LOW("Retail Trade"),
  SE("Retail Trade"),
  CVS("Retail Trade"),

  PG("Consumer Non-Durables"),
  KO("Consumer Non-Durables"),
  PM("Consumer Non-Durables"),
  PEP("Consumer Non-Durables"),
  UL("Consumer Non-Durables"),
  BUD("Consumer Non-Durables"),
  BTI("Consumer Non-Durables"),
  MO("Consumer Non-Durables"),
  MDLZ("Consumer Non-Durables"),
  NKE("Consumer Non-Durables"),

  XOM("Energy Minerals"),
  CVX("Energy Minerals"),
  SHEL("Energy Minerals"),
  TTE("Energy Minerals"),
  COP("Energy Minerals"),
  BP("Energy Minerals"),
  EQNR("Energy Minerals"),
  CNQ("Energy Minerals"),
  EOG("Energy Minerals"),
  MPC("Energy Minerals"),

  DIS("Consumer Services"),
  MCD("Consumer Services"),
  BKNG("Consumer Services"),
  CMCSA("Consumer Services"),
  CHTR("Consumer Services"),
  SBUX("Consumer Services"),
  CTAS("Consumer Services"),
  ABNB("Consumer Services"),
  RCL("Consumer Services"),
  MAR("Consumer Services"),

  CAT("Producer Manufacturing"),
  DE("Producer Manufacturing"),
  GEV("Producer Manufacturing"),
  LRCX("Producer Manufacturing"),
  TT("Producer Manufacturing"),
  MMM("Producer Manufacturing"),
  ITW("Producer Manufacturing"),
  JCI("Producer Manufacturing"),
  CARR("Producer Manufacturing"),
  PCAR("Producer Manufacturing"),

  TSLA("Consumer Durables"),
  TM("Consumer Durables"),
  RACE("Consumer Durables"),
  HMC("Consumer Durables"),
  GM("Consumer Durables"),
  F("Consumer Durables"),
  DHI("Consumer Durables"),
  STLA("Consumer Durables"),
  LEN("Consumer Durables"),
  LI("Consumer Durables"),

  NEE("Utilities"),
  SO("Utilities"),
  CEG("Utilities"),
  DUK("Utilities"),
  NGG("Utilities"),
  VST("Utilities"),
  AEP("Utilities"),
  SRE("Utilities"),
  D("Utilities"),
  EXC("Utilities"),


}