package com.skrymer.udgaard.model

enum class StockSymbol(val market: MarketSymbol) {
  // Technology
  MSFT(MarketSymbol.XLK),
  GOOG(MarketSymbol.XLK),
  META(MarketSymbol.XLK),
  ORCL(MarketSymbol.XLK),
  NFLX(MarketSymbol.XLK),
  SAP(MarketSymbol.XLK),
  PLTR(MarketSymbol.XLK),
  IBM(MarketSymbol.XLK),
  CRM(MarketSymbol.XLK),
  INTU(MarketSymbol.XLK),


  // Finance
  JPM(MarketSymbol.XLF),
  V(MarketSymbol.XLF),
  MA(MarketSymbol.XLF),
  BAC(MarketSymbol.XLF),
  WFC(MarketSymbol.XLF),
  MS(MarketSymbol.XLF),
  AXP(MarketSymbol.XLF),
  HSBC(MarketSymbol.XLF),
  GS(MarketSymbol.XLF),
  RY(MarketSymbol.XLF),

  LLY(MarketSymbol.XLV),
  JNJ(MarketSymbol.XLV),
  NVO(MarketSymbol.XLV),
  ABBV(MarketSymbol.XLV),
  ABT(MarketSymbol.XLV),
  NVS(MarketSymbol.XLV),
  AZN(MarketSymbol.XLV),
  MRK(MarketSymbol.XLV),
  ISRG(MarketSymbol.XLV),
  AMGN(MarketSymbol.XLV),

//  AMZN("Retail Trade"),
//  WMT("Retail Trade"),
//  COST("Retail Trade"),
//  HD("Retail Trade"),
//  BABA("Retail Trade"),
//  PDD("Retail Trade"),
//  TJX("Retail Trade"),
//  MELI("Retail Trade"),
//  LOW("Retail Trade"),
//  SE("Retail Trade"),
//  CVS("Retail Trade"),
//
//  PG("Consumer Non-Durables"),
//  KO("Consumer Non-Durables"),
//  PM("Consumer Non-Durables"),
//  PEP("Consumer Non-Durables"),
//  UL("Consumer Non-Durables"),
//  BUD("Consumer Non-Durables"),
//  BTI("Consumer Non-Durables"),
//  MO("Consumer Non-Durables"),
//  MDLZ("Consumer Non-Durables"),
//  NKE("Consumer Non-Durables"),
//
//  XOM("Energy Minerals"),
//  CVX("Energy Minerals"),
//  SHEL("Energy Minerals"),
//  TTE("Energy Minerals"),
//  COP("Energy Minerals"),
//  BP("Energy Minerals"),
//  EQNR("Energy Minerals"),
//  CNQ("Energy Minerals"),
//  EOG("Energy Minerals"),
//  MPC("Energy Minerals"),
//
//  DIS("Consumer Services"),
//  MCD("Consumer Services"),
//  BKNG("Consumer Services"),
//  CMCSA("Consumer Services"),
//  CHTR("Consumer Services"),
//  SBUX("Consumer Services"),
//  CTAS("Consumer Services"),
//  ABNB("Consumer Services"),
//  RCL("Consumer Services"),
//  MAR("Consumer Services"),
//
//  CAT("Producer Manufacturing"),
//  DE("Producer Manufacturing"),
//  GEV("Producer Manufacturing"),
//  LRCX("Producer Manufacturing"),
//  TT("Producer Manufacturing"),
//  MMM("Producer Manufacturing"),
//  ITW("Producer Manufacturing"),
//  JCI("Producer Manufacturing"),
//  CARR("Producer Manufacturing"),
//  PCAR("Producer Manufacturing"),
//
//  TSLA("Consumer Durables"),
//  TM("Consumer Durables"),
//  RACE("Consumer Durables"),
//  HMC("Consumer Durables"),
//  GM("Consumer Durables"),
//  F("Consumer Durables"),
//  DHI("Consumer Durables"),
//  STLA("Consumer Durables"),
//  LEN("Consumer Durables"),
//  LI("Consumer Durables"),
//
//  NEE("Utilities"),
//  SO("Utilities"),
//  CEG("Utilities"),
//  DUK("Utilities"),
//  NGG("Utilities"),
//  VST("Utilities"),
//  AEP("Utilities"),
//  SRE("Utilities"),
//  D("Utilities"),
//  EXC("Utilities"),


}