package com.skrymer.udgaard.model

enum class StockSymbol(val market: MarketSymbol) {
  // Technology
  NVDA(MarketSymbol.XLK),
  AAPL(MarketSymbol.XLK),
  MSFT(MarketSymbol.XLK),
  TSM(MarketSymbol.XLK),
  AVGO(MarketSymbol.XLK),
  ORCL(MarketSymbol.XLK),
  CRM(MarketSymbol.XLK),
  ADBE(MarketSymbol.XLK),
  CSCO(MarketSymbol.XLK),
  INTC(MarketSymbol.XLK),
  IBM(MarketSymbol.XLK),
  ACN(MarketSymbol.XLK),
  INTU(MarketSymbol.XLK),
  PLTR(MarketSymbol.XLK),
  AMD(MarketSymbol.XLK),
  TXN(MarketSymbol.XLK),
  QCOM(MarketSymbol.XLK),

  // Finance
  JPM(MarketSymbol.XLF),
  V(MarketSymbol.XLF),
  MA(MarketSymbol.XLF),
  BAC(MarketSymbol.XLF),
  WFC(MarketSymbol.XLF),
  GS(MarketSymbol.XLF),
  MS(MarketSymbol.XLF),
  C(MarketSymbol.XLF),
  BLK(MarketSymbol.XLF),
  AXP(MarketSymbol.XLF),
  CB(MarketSymbol.XLF),
  PNC(MarketSymbol.XLF),
  USB(MarketSymbol.XLF),
  KEY(MarketSymbol.XLF),
  TROW(MarketSymbol.XLF),
  ALLY(MarketSymbol.XLF),
  SOFI(MarketSymbol.XLF),
  APO(MarketSymbol.XLF),
  SYF(MarketSymbol.XLF),

  // Health
  LLY(MarketSymbol.XLV),
  UNH(MarketSymbol.XLV),
  NVO(MarketSymbol.XLV),
  JNJ(MarketSymbol.XLV),
  MRK(MarketSymbol.XLV),
  ABT(MarketSymbol.XLV),
  PFE(MarketSymbol.XLV),
  AMGN(MarketSymbol.XLV),
  TMO(MarketSymbol.XLV),
  DHR(MarketSymbol.XLV),
  VRTX(MarketSymbol.XLV),
  SYK(MarketSymbol.XLV),
  ISRG(MarketSymbol.XLV),
  MDT(MarketSymbol.XLV),
  GILD(MarketSymbol.XLV),
  CVS(MarketSymbol.XLV),
  BDX(MarketSymbol.XLV),
  ELD(MarketSymbol.XLV),
  HCA(MarketSymbol.XLV),
  REGN(MarketSymbol.XLV),
  CAH(MarketSymbol.XLV),

  // Industrials
  GE(MarketSymbol.XLI),
  CAT(MarketSymbol.XLI),
  RTX(MarketSymbol.XLI),
  UNP(MarketSymbol.XLI),
  HON(MarketSymbol.XLI),
  BA(MarketSymbol.XLI),
  DE(MarketSymbol.XLI),
  ADP(MarketSymbol.XLI),
  LMT(MarketSymbol.XLI),
  UPS(MarketSymbol.XLI),
  PH(MarketSymbol.XLI),
  WM(MarketSymbol.XLI),
  MMM(MarketSymbol.XLI),
  CTAS(MarketSymbol.XLI),
  ITW(MarketSymbol.XLI),
  TDG(MarketSymbol.XLI),
  GD(MarketSymbol.XLI),
  NOC(MarketSymbol.XLI),
  RSG(MarketSymbol.XLI),
  CARR(MarketSymbol.XLI),

  // Materials
  LIN(MarketSymbol.XLB),
  BHP(MarketSymbol.XLB),
  SHW(MarketSymbol.XLB),
  FCX(MarketSymbol.XLB),
  APD(MarketSymbol.XLB),
  RIO(MarketSymbol.XLB),
  SCCO(MarketSymbol.XLB),
  ECL(MarketSymbol.XLB),
  NUE(MarketSymbol.XLB),
  DOW(MarketSymbol.XLB),
  DD(MarketSymbol.XLB),
  NEM(MarketSymbol.XLB),
  PPG(MarketSymbol.XLB),
  IP(MarketSymbol.XLB),
  ALB(MarketSymbol.XLB),
  CMC(MarketSymbol.XLB),
  EXP(MarketSymbol.XLB),
  PAAS(MarketSymbol.XLB),
  KGC(MarketSymbol.XLB),
  SQM(MarketSymbol.XLB),

  // Energy
  XOM(MarketSymbol.XLE),
  CVX(MarketSymbol.XLE),
  SHEL(MarketSymbol.XLE),
  PTR(MarketSymbol.XLE),
  TTE(MarketSymbol.XLE),
  COP(MarketSymbol.XLE),
  BP(MarketSymbol.XLE),
  ENB(MarketSymbol.XLE),
  CNQ(MarketSymbol.XLE),
  EOG(MarketSymbol.XLE),
  SLB(MarketSymbol.XLE),
  MPC(MarketSymbol.XLE),
  PXD(MarketSymbol.XLE),
  OXY(MarketSymbol.XLE),
  VLO(MarketSymbol.XLE),
  WMB(MarketSymbol.XLE),
  CTRA(MarketSymbol.XLE),
  ET(MarketSymbol.XLE),

  // Utilities
  NEE(MarketSymbol.XLU),
  SO(MarketSymbol.XLU),
  DUK(MarketSymbol.XLU),
  D(MarketSymbol.XLU),
  AEP(MarketSymbol.XLU),
  SRE(MarketSymbol.XLU),
  EXC(MarketSymbol.XLU),
  XEL(MarketSymbol.XLU),
  ED(MarketSymbol.XLU),
  PEG(MarketSymbol.XLU),
  EIX(MarketSymbol.XLU),
  WEC(MarketSymbol.XLU),
  AWK(MarketSymbol.XLU),
  DTE(MarketSymbol.XLU),
  ETR(MarketSymbol.XLU),
  FE(MarketSymbol.XLU),
  ES(MarketSymbol.XLU),
  PPL(MarketSymbol.XLU),
  CNP(MarketSymbol.XLU),
  ATO(MarketSymbol.XLU),

  // Consumer discretionary
  AMZN(MarketSymbol.XLY),
  TSLA(MarketSymbol.XLY),
  HD(MarketSymbol.XLY),
  MCD(MarketSymbol.XLY),
  NKE(MarketSymbol.XLY),
  LOW(MarketSymbol.XLY),
  TJX(MarketSymbol.XLY),
  BKNG(MarketSymbol.XLY),
  SBUX(MarketSymbol.XLY),
  PDD(MarketSymbol.XLY),
  GM(MarketSymbol.XLY),
  F(MarketSymbol.XLY),
  MAR(MarketSymbol.XLY),
  TGT(MarketSymbol.XLY),
  CMG(MarketSymbol.XLY),
  LULU(MarketSymbol.XLY),
  ROST(MarketSymbol.XLY),
  ORLY(MarketSymbol.XLY),
  AZO(MarketSymbol.XLY),
  DHI(MarketSymbol.XLY),

  // Consumer staples
  WMT(MarketSymbol.XLP),
  PG(MarketSymbol.XLP),
  COST(MarketSymbol.XLP),
  KO(MarketSymbol.XLP),
  PEP(MarketSymbol.XLP),
  UL(MarketSymbol.XLP),
  MDLZ(MarketSymbol.XLP),
  CL(MarketSymbol.XLP),
  KMB(MarketSymbol.XLP),
  GIS(MarketSymbol.XLP),
  KHC(MarketSymbol.XLP),
  SYY(MarketSymbol.XLP),
  ADM(MarketSymbol.XLP),
  K(MarketSymbol.XLP),
  CLX(MarketSymbol.XLP),
  HSY(MarketSymbol.XLP),
  CHD(MarketSymbol.XLP),
  KR(MarketSymbol.XLP),
  CPB(MarketSymbol.XLP),
  CAG(MarketSymbol.XLP),

  // Communication services
  GOOGL(MarketSymbol.XLC),
  META(MarketSymbol.XLC),
  NFLX(MarketSymbol.XLC),
  TMUS(MarketSymbol.XLC),
  DIS(MarketSymbol.XLC),
  VZ(MarketSymbol.XLC),
  T(MarketSymbol.XLC),
  CMCSA(MarketSymbol.XLC),
  ABNB(MarketSymbol.XLC),
  DASH(MarketSymbol.XLC),
  CHTR(MarketSymbol.XLC),
  TTWO(MarketSymbol.XLC),
  EA(MarketSymbol.XLC),
  WBD(MarketSymbol.XLC),
  ZM(MarketSymbol.XLC),
  FWONK(MarketSymbol.XLC),
  PINS(MarketSymbol.XLC),
  FOXA(MarketSymbol.XLC),
  RBLX(MarketSymbol.XLC),
  LYV(MarketSymbol.XLC),

  // Real estate
  AMT(MarketSymbol.XLRE),
  PLD(MarketSymbol.XLRE),
  EQIX(MarketSymbol.XLRE),
  SPG(MarketSymbol.XLRE),
  WELL(MarketSymbol.XLRE),
  DLR(MarketSymbol.XLRE),
  CCI(MarketSymbol.XLRE),
  O(MarketSymbol.XLRE),
  PSA(MarketSymbol.XLRE),
  EXR(MarketSymbol.XLRE),
  AVB(MarketSymbol.XLRE),
  VICI(MarketSymbol.XLRE),
  VTR(MarketSymbol.XLRE),
  SBAC(MarketSymbol.XLRE),
  BXP(MarketSymbol.XLRE),
  ARE(MarketSymbol.XLRE),
  KIM(MarketSymbol.XLRE),
  MAA(MarketSymbol.XLRE),
  WPC(MarketSymbol.XLRE),
  ESS(MarketSymbol.XLRE),
}