package com.skrymer.udgaard.service

import com.skrymer.udgaard.controller.dto.ApiCredentialsDto
import org.slf4j.LoggerFactory
import org.springframework.stereotype.Service
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.util.*

@Service
class SettingsService {
  private val logger = LoggerFactory.getLogger(SettingsService::class.java)

  private val configDir = File(System.getProperty("user.home"), ".trading-app")
  private val configFile = File(configDir, "config.properties")

  init {
    if (!configDir.exists()) {
      configDir.mkdirs()
      logger.info("Created config directory: ${configDir.absolutePath}")
    }

    if (!configFile.exists()) {
      createTemplateConfigFile()
    }
  }

  fun getCredentials(): ApiCredentialsDto {
    if (!configFile.exists()) {
      logger.warn("Config file not found: ${configFile.absolutePath}")
      return ApiCredentialsDto()
    }

    val properties = Properties()
    FileInputStream(configFile).use { properties.load(it) }

    return ApiCredentialsDto(
      ibkrAccountId = properties.getProperty("ibkr.account.id", ""),
      ibkrFlexQueryId = properties.getProperty("ibkr.flexquery.id", ""),
    )
  }

  fun saveCredentials(credentials: ApiCredentialsDto) {
    val properties = Properties()

    if (configFile.exists()) {
      FileInputStream(configFile).use { properties.load(it) }
    }

    properties.setProperty("ibkr.account.id", credentials.ibkrAccountId)
    properties.setProperty("ibkr.flexquery.id", credentials.ibkrFlexQueryId)

    FileOutputStream(configFile).use { output ->
      properties.store(output, "Trading App Configuration - Generated by Settings UI")
    }

    logger.info("Credentials saved to: ${configFile.absolutePath}")

    System.setProperty("ibkr.account.id", credentials.ibkrAccountId)
    System.setProperty("ibkr.flexquery.id", credentials.ibkrFlexQueryId)
  }

  fun getCredentialsStatus(): Map<String, Boolean> {
    val credentials = getCredentials()
    return mapOf(
      "ibkrConfigured" to (credentials.ibkrAccountId.isNotBlank() && credentials.ibkrFlexQueryId.isNotBlank()),
      "configFileExists" to configFile.exists(),
    )
  }

  private fun createTemplateConfigFile() {
    val template =
      """
      # Trading App Configuration
      # Enter your API credentials below

      # Interactive Brokers Configuration
      # Get Account ID from IBKR portal, Flex Query ID from Flex Query setup
      ibkr.account.id=
      ibkr.flexquery.id=
      """.trimIndent()

    configFile.writeText(template)
    logger.info("Created template config file: ${configFile.absolutePath}")
  }
}
