package com.skrymer.udgaard.service

import com.skrymer.udgaard.controller.dto.ApiCredentialsDto
import org.slf4j.LoggerFactory
import org.springframework.stereotype.Service
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.util.*

@Service
class SettingsService {
  private val logger = LoggerFactory.getLogger(SettingsService::class.java)

  private val configDir = File(System.getProperty("user.home"), ".trading-app")
  private val configFile = File(configDir, "config.properties")

  init {
    // Create config directory if it doesn't exist
    if (!configDir.exists()) {
      configDir.mkdirs()
      logger.info("Created config directory: ${configDir.absolutePath}")
    }

    // Create template config file if it doesn't exist
    if (!configFile.exists()) {
      createTemplateConfigFile()
    }
  }

  fun getCredentials(): ApiCredentialsDto {
    if (!configFile.exists()) {
      logger.warn("Config file not found: ${configFile.absolutePath}")
      return ApiCredentialsDto()
    }

    val properties = Properties()
    FileInputStream(configFile).use { properties.load(it) }

    return ApiCredentialsDto(
      ovtlyrToken = properties.getProperty("ovtlyr.cookies.token", ""),
      ovtlyrUserId = properties.getProperty("ovtlyr.cookies.userid", ""),
      alphaVantageApiKey = properties.getProperty("alphavantage.api.key", ""),
    )
  }

  fun saveCredentials(credentials: ApiCredentialsDto) {
    val properties = Properties()

    // Load existing properties if file exists
    if (configFile.exists()) {
      FileInputStream(configFile).use { properties.load(it) }
    }

    // Update with new credentials
    properties.setProperty("ovtlyr.cookies.token", credentials.ovtlyrToken)
    properties.setProperty("ovtlyr.cookies.userid", credentials.ovtlyrUserId)
    properties.setProperty("alphavantage.api.key", credentials.alphaVantageApiKey)

    // Save to file
    FileOutputStream(configFile).use { output ->
      properties.store(output, "Trading App Configuration - Generated by Settings UI")
    }

    logger.info("Credentials saved to: ${configFile.absolutePath}")

    // Update system properties so they're available immediately
    System.setProperty("ovtlyr.cookies.token", credentials.ovtlyrToken)
    System.setProperty("ovtlyr.cookies.userid", credentials.ovtlyrUserId)
    System.setProperty("alphavantage.api.key", credentials.alphaVantageApiKey)
  }

  fun getCredentialsStatus(): Map<String, Boolean> {
    val credentials = getCredentials()
    return mapOf(
      "ovtlyrConfigured" to (credentials.ovtlyrToken.isNotBlank() && credentials.ovtlyrUserId.isNotBlank()),
      "alphaVantageConfigured" to credentials.alphaVantageApiKey.isNotBlank(),
      "configFileExists" to configFile.exists(),
    )
  }

  private fun createTemplateConfigFile() {
    val template =
      """
      # Trading App Configuration
      # Enter your API credentials below

      # Ovtlyr API Credentials
      # Get these from https://console.ovtlyr.com (login and check cookies in browser DevTools)
      ovtlyr.cookies.token=
      ovtlyr.cookies.userid=

      # Alpha Vantage API Key
      # Get your free API key at: https://www.alphavantage.co/support/#api-key
      alphavantage.api.key=
      """.trimIndent()

    configFile.writeText(template)
    logger.info("Created template config file: ${configFile.absolutePath}")
  }
}
